openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
servers:
  - url: https://24140260-278e-4d9e-899c-daad5cfee0f0.mock.pstmn.io
    description: Local server
paths:
  /tasks:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskName:
                  type: string
                  example: Task 1
      responses:
        201:
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    get:
      summary: Load list of tasks
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /tasks/{taskId}:
    get:
      summary: Get task by Id
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Task detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Task deleted
  /tasks/{taskId}/status:
    patch:
      summary: Change a task status
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - done
                  example: done
      responses:
        204:
          description: Task updated
        404:
          description: Task not found
        400:
          description: Invalid status  
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: number
          readOnly: true
        taskName:
          type: string
        remainingHours:
          type: integer
        isCompleted:
          type: boolean
          default: false
      required:
        - taskName
        - remainingHours